# Generated by Django 4.2.6 on 2023-10-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_sale_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablebill',
            name='items',
        ),
        migrations.AddField(
            model_name='tablebill',
            name='items',
            field=models.ManyToManyField(blank=True, to='app.item_sale'),
        ),
    ]
