# Generated by Django 4.2.6 on 2023-10-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_month_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.month')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.year')),
            ],
        ),
    ]
